(function(){
  ensureStore();
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const orders=()=>{try{return JSON.parse(localStorage.getItem('bookOrders')||'[]')}catch{return[]}};
  const enquiries=()=>{try{return JSON.parse(localStorage.getItem('bookEnquiries')||'[]')}catch{return[]}};
  const analytics=()=>getAnalytics();
  let store=getStore();
  function toast(m){const t=$('.toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1600)}
  function save(){saveStore(store);store=getStore();toast('Saved')}
  function unlocked(){return sessionStorage.getItem('adminUnlocked')==='1'}
  function lock(){sessionStorage.removeItem('adminUnlocked');$('#adminLock').classList.remove('hidden');$('#adminPinInput').value='';setTimeout(()=>$('#adminPinInput')?.focus(),50)}
  function show(id){$$('.admin-section').forEach(x=>x.classList.toggle('hidden',x.id!==id));$$('.admin-side button').forEach(x=>x.classList.toggle('active',x.dataset.target===id));if(id==='dashboard')dashboard();if(id==='analytics')renderAnalytics();if(id==='books')renderBooks();if(id==='orders')renderOrders();if(id==='delivery')loadDelivery();if(id==='offers')loadOffers();if(id==='gallery')renderGallery();if(id==='enquiries')renderEnquiries();if(id==='home')loadHome();if(id==='contact')loadContact();if(id==='seo')loadSeo();if(id==='security')loadSecurity();window.scrollTo({top:0,behavior:'smooth'})}
  $('#adminLoginForm').onsubmit=e=>{e.preventDefault();store=getStore();const entered=$('#adminPinInput').value.trim();if(entered&&(entered===String(store.settings.adminPin||'2468'))){sessionStorage.setItem('adminUnlocked','1');$('#adminLock').classList.add('hidden');toast('Admin unlocked');return}$('#adminLoginError').textContent='Incorrect PIN.'};
  $('#adminLogout').onclick=lock;
  if(unlocked())$('#adminLock').classList.add('hidden');
  $$('.admin-side button').forEach(b=>b.onclick=()=>show(b.dataset.target));$$('[data-quick]').forEach(b=>b.onclick=()=>show(b.dataset.quick));
  function activeOfferText(){const s=store.settings||{};if(!s.offerEnabled||s.offerType==='none')return 'No active offer';if(s.offerType==='percent10')return `10% OFF${s.offerMinPurchase?` above ${money(s.offerMinPurchase)}`:''}`;if(s.offerType==='bogo500')return `Buy 1 Get 1 · free book up to ${money(s.bogoFreeMaxPrice||500)}`;return 'Buy Any 2, Get 1 Free';}
  function dashboard(){const os=orders(),en=enquiries(),s=store.settings||{};$('#dashStats').innerHTML=`<div class="stat"><span class="meta">Books</span><b>${store.books.length}</b><small>catalog items</small></div><div class="stat"><span class="meta">In Stock</span><b>${store.books.filter(b=>b.active!==false&&Number(b.stock||0)>0).length}</b><small>available titles</small></div><div class="stat"><span class="meta">Orders</span><b>${os.length}</b><small>prototype orders</small></div><div class="stat"><span class="meta">Enquiries</span><b>${en.length}</b><small>customer messages</small></div>`;$('#ruleSummary').innerHTML=`<div class="rule-card"><span>Delivery</span><b>${s.deliveryEnabled?'ON':'OFF'}</b><small>${s.deliveryEnabled?`${money(s.deliveryFeePerKm)} / KM · minimum ${money(s.deliveryMinimumFee)}`:'Unavailable'}</small></div><div class="rule-card"><span>Free Delivery</span><b>${s.freeShippingEnabled?'ON':'OFF'}</b><small>${s.freeShippingEnabled?`Above ${money(s.freeShippingThreshold)}`:'Disabled'}</small></div><div class="rule-card"><span>COD</span><b>${s.codEnabled?'ON':'OFF'}</b><small>Checkout option</small></div><div class="rule-card"><span>Offer</span><b>${s.offerEnabled?'ON':'OFF'}</b><small>${esc(activeOfferText())}</small></div>`;$('#recentOrders').innerHTML=os.slice(0,5).map(o=>`<div class="mini-row"><div><b>${esc(o.id)}</b><div class="meta">${esc(o.customer?.name||'Guest')} · ${esc(o.date||'')}</div></div><strong>${money(o.total)}</strong></div>`).join('')||`<div class="empty-lite">No orders yet.</div>`}
  function renderAnalytics(){const a=analytics();const ev=a.events||{};$('#analyticsStats').innerHTML=`<div class="stat"><span class="meta">Page Views</span><b>${a.pageViews||0}</b><small>this browser</small></div><div class="stat"><span class="meta">Add to Cart</span><b>${ev.add_to_cart||0}</b><small>events</small></div><div class="stat"><span class="meta">Checkout Starts</span><b>${ev.checkout_start||0}</b><small>events</small></div><div class="stat"><span class="meta">Orders Placed</span><b>${ev.order_placed||0}</b><small>events</small></div>`;const pageRows=Object.entries(a.pages||{}).sort((x,y)=>y[1]-x[1]).slice(0,8);$('#analyticsPages').innerHTML=pageRows.map(([k,v])=>`<div class="mini-row"><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<div class="empty-lite">No page views yet.</div>';const views=a.bookViews||{},booksById=Object.fromEntries(store.books.map(b=>[b.id,b]));const bookRows=Object.entries(views).sort((x,y)=>y[1]-x[1]).slice(0,8);$('#analyticsBooks').innerHTML=bookRows.map(([id,v])=>`<div class="mini-row"><span>${esc(booksById[id]?.title||id)}</span><b>${v}</b></div>`).join('')||'<div class="empty-lite">No book views yet.</div>'}
  $('#clearAnalytics').onclick=()=>{if(confirm('Clear prototype analytics?')){localStorage.removeItem('bookAnalytics');renderAnalytics()}};
  function loadHome(){const s=store.settings;['brandName','tagline','heroTitle','heroText','supportText'].forEach(k=>{const e=$('#s_'+k);if(e)e.value=s[k]||''})} $('#settingsForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);for(const[k,v]of fd.entries())store.settings[k]=String(v);save()};
  function loadContact(){const s=store.settings;$('#s_whatsapp').value=s.whatsapp||'';$('#s_phone').value=s.phone||'';$('#s_locationLabel').value=s.locationLabel||'';$('#s_locationUrl').value=s.locationUrl||'';$('#s_address').value=s.address||'';$('#s_supportText2').value=s.supportText||''} $('#contactForm').onsubmit=e=>{e.preventDefault();store.settings.whatsapp=$('#s_whatsapp').value.trim();store.settings.phone=$('#s_phone').value.trim();store.settings.locationLabel=$('#s_locationLabel').value.trim();store.settings.locationUrl=$('#s_locationUrl').value.trim();store.settings.address=$('#s_address').value.trim();store.settings.supportText=$('#s_supportText2').value.trim();save()};
  function clearBookForm(){$('#bookForm').reset();$('#bookId').value='';$('#bookCoverData').value='';$('#bookActive').checked=true;$('#bookStock').value='0';$('#bookPreview').innerHTML='<span class="meta">No cover selected.</span>'}
  function fillBook(id){const b=store.books.find(x=>x.id===id);if(!b)return;$('#bookId').value=b.id;$('#bookTitle').value=b.title||'';$('#bookAuthor').value=b.author||'';$('#bookPrice').value=b.price??0;$('#bookFormat').value=b.format||'Paperback';$('#bookCategory').value=b.category||'';$('#bookStock').value=Number(b.stock||0);$('#bookRating').value=b.rating??0;$('#bookReviews').value=b.reviews??0;$('#bookDescription').value=b.description||'';$('#bookAmazonUrl').value=b.amazonUrl||'';$('#bookActive').checked=b.active!==false;$('#bookCoverUrl').value=b.cover&&String(b.cover).startsWith('data:')?'':(b.cover||'');$('#bookCoverData').value=b.cover&&String(b.cover).startsWith('data:')?b.cover:'';$('#bookPreview').innerHTML=b.cover?`<img src="${esc(b.cover)}" alt="${esc(b.title)}" class="admin-cover-preview">`:'<span class="meta">No cover selected.</span>';show('books')}
  function filteredBooks(){const q=($('#bookAdminSearch').value||'').toLowerCase();return store.books.filter(b=>(b.title+' '+b.author+' '+b.category).toLowerCase().includes(q))}
  function renderBooks(){const tb=$('#booksTable');tb.innerHTML=filteredBooks().map(b=>{const available=b.active!==false&&Number(b.stock||0)>0;return `<tr><td><div class="table-book"><div class="table-thumb">${b.cover?`<img src="${esc(b.cover)}" alt="">`:'📘'}</div><div><b>${esc(b.title)}</b><div class="meta">${esc(b.author)}</div></div></div></td><td><strong>${money(b.price)}</strong></td><td>${Number(b.stock||0)}</td><td><span class="status-pill ${available?'success':''}">${available?'In Stock':'Out of Stock'}</span></td><td>${b.amazonUrl?`<a href="${esc(b.amazonUrl)}" target="_blank" rel="noopener noreferrer" class="text-link">Open Amazon ↗</a>`:'—'}</td><td class="action-cell"><button class="btn btn-light" data-edit="${esc(b.id)}">Edit</button><button class="btn btn-danger" data-del="${esc(b.id)}">Delete</button></td></tr>`}).join('')||`<tr><td colspan="6" class="empty-lite">No books match your search.</td></tr>`;$$('[data-edit]').forEach(b=>b.onclick=()=>fillBook(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this book?'))return;store.books=store.books.filter(x=>x.id!==b.dataset.del);save();renderBooks()})}
  $('#bookAdminSearch').oninput=renderBooks;$('#newBook').onclick=()=>{clearBookForm();show('books');$('#bookTitle').focus()};$('#cancelBook').onclick=clearBookForm;$('#bookCoverFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){toast('Please use an image under 2MB in prototype');e.target.value='';return}const r=new FileReader();r.onload=()=>{$('#bookCoverData').value=r.result;$('#bookPreview').innerHTML=`<img src="${esc(r.result)}" alt="Preview" class="admin-cover-preview">`};r.readAsDataURL(f)};
  $('#bookForm').onsubmit=e=>{e.preventDefault();const id=$('#bookId').value||('b'+Date.now()),existing=store.books.find(x=>x.id===id),cover=$('#bookCoverData').value||$('#bookCoverUrl').value.trim()||existing?.cover||'';const item={id,title:$('#bookTitle').value.trim()||'Untitled Book',author:$('#bookAuthor').value.trim()||'Author Name',price:Number($('#bookPrice').value||0),format:$('#bookFormat').value,category:$('#bookCategory').value.trim()||'Others',rating:Number($('#bookRating').value||0),reviews:Number($('#bookReviews').value||0),cover,featured:existing?.featured||false,stock:Math.max(0,Number($('#bookStock').value||0)),active:$('#bookActive').checked,amazonUrl:$('#bookAmazonUrl').value.trim(),description:$('#bookDescription').value.trim()};if(existing)store.books=store.books.map(x=>x.id===id?item:x);else store.books.push(item);save();clearBookForm();renderBooks()};
  function renderOrders(){const tb=$('#ordersTable'),arr=orders();tb.innerHTML=arr.map(o=>{const count=(o.items||[]).reduce((s,x)=>s+Number(x.qty||0),0),status=o.status||'Placed';return `<tr><td><b>${esc(o.id)}</b></td><td>${esc(o.date)}</td><td>${esc(o.customer?.name||'')}</td><td>${esc(o.customer?.phone||'')}</td><td>${count}</td><td><strong>${money(o.total)}</strong></td><td><select class="select order-status" data-order-status="${esc(o.id)}" style="min-width:130px"><option ${status==='Placed'?'selected':''}>Placed</option><option ${status==='Confirmed'?'selected':''}>Confirmed</option><option ${status==='Packed'?'selected':''}>Packed</option><option ${status==='Shipped'?'selected':''}>Shipped</option><option ${status==='Delivered'?'selected':''}>Delivered</option><option ${status==='Cancelled'?'selected':''}>Cancelled</option></select></td></tr>`}).join('')||`<tr><td colspan="7" class="empty-lite">No orders yet.</td></tr>`;$$('[data-order-status]').forEach(s=>s.onchange=()=>{const arr2=orders();const next=arr2.find(o=>o.id===s.dataset.orderStatus);if(next){next.status=s.value;localStorage.setItem('bookOrders',JSON.stringify(arr2));dashboard();toast('Order status updated')}})} $('#clearOrders').onclick=()=>{if(confirm('Clear all prototype orders?')){localStorage.removeItem('bookOrders');dashboard();renderOrders()}};
  function loadDelivery(){const s=store.settings||{};$('#deliveryEnabled').checked=Boolean(s.deliveryEnabled);$('#deliveryFeePerKm').value=Number(s.deliveryFeePerKm||0);$('#deliveryMinimumFee').value=Number(s.deliveryMinimumFee||0);$('#freeShippingEnabled').checked=Boolean(s.freeShippingEnabled);$('#freeShippingThreshold').value=Number(s.freeShippingThreshold||0)} $('#deliveryForm').onsubmit=e=>{e.preventDefault();store.settings.deliveryEnabled=$('#deliveryEnabled').checked;store.settings.deliveryFeePerKm=Math.max(0,Number($('#deliveryFeePerKm').value||0));store.settings.deliveryMinimumFee=Math.max(0,Number($('#deliveryMinimumFee').value||0));store.settings.freeShippingEnabled=$('#freeShippingEnabled').checked;store.settings.freeShippingThreshold=Math.max(0,Number($('#freeShippingThreshold').value||0));save()};
  function loadOffers(){const s=store.settings||{};$('#offerEnabled').checked=Boolean(s.offerEnabled);$('#offerType').value=s.offerType||'none';$('#offerMinPurchase').value=Number(s.offerMinPurchase??500);$('#bogoFreeMaxPrice').value=Number(s.bogoFreeMaxPrice??500);$('#offerTitle').value=s.offerTitle||'';$('#offerText').value=s.offerText||''} $('#offersForm').onsubmit=e=>{e.preventDefault();store.settings.offerEnabled=$('#offerEnabled').checked;store.settings.offerType=$('#offerType').value;store.settings.offerMinPurchase=Math.max(0,Number($('#offerMinPurchase').value||0));store.settings.bogoFreeMaxPrice=Math.max(0,Number($('#bogoFreeMaxPrice').value||0));store.settings.offerTitle=$('#offerTitle').value.trim();store.settings.offerText=$('#offerText').value.trim();save()};
  function renderGallery(){const el=$('#galleryAdminGrid');el.innerHTML=store.gallery.map(g=>`<article class="admin-gallery-card"><div class="admin-gallery-image">${g.image?`<img src="${esc(g.image)}" alt="${esc(g.title)}">`:'📚'}</div><div class="admin-gallery-body"><b>${esc(g.title)}</b><p class="meta">${esc(g.caption||'')}</p><button class="btn btn-danger" data-gdel="${esc(g.id)}">Delete</button></div></article>`).join('')||`<div class="empty-lite">No gallery items.</div>`;$$('[data-gdel]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this gallery item?'))return;store.gallery=store.gallery.filter(x=>x.id!==b.dataset.gdel);save();renderGallery()})}
  $('#galleryForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),img=$('#galleryData').value||$('#galleryUrl').value.trim();if(!img){toast('Choose an image or paste an image URL');return}store.gallery.push({id:'g'+Date.now(),title:String(fd.get('title')||'Untitled'),caption:String(fd.get('caption')||''),image:img});save();e.target.reset();$('#galleryData').value='';renderGallery()};$('#galleryFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){toast('Please use an image under 2MB in prototype');e.target.value='';return}const r=new FileReader();r.onload=()=>$('#galleryData').value=r.result;r.readAsDataURL(f)};
  function renderEnquiries(){const tb=$('#enquiriesTable'),arr=enquiries();tb.innerHTML=arr.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name||'')}</b></td><td>${esc(x.phone||'')}</td><td>${esc(x.email||'')}</td><td class="message-cell">${esc(x.message||'')}</td><td>${esc(x.date||'')}</td><td><a class="btn btn-light" href="tel:${esc(x.phone||'')}">Call</a></td></tr>`).join('')||`<tr><td colspan="7" class="empty-lite">No enquiries yet.</td></tr>`} $('#clearEnquiries').onclick=()=>{if(confirm('Clear all enquiries?')){localStorage.removeItem('bookEnquiries');dashboard();renderEnquiries()}};
  function loadSeo(){const s=store.settings||{};$('#seoTitle').value=s.seoTitle||'';$('#seoDescription').value=s.seoDescription||'';$('#seoKeywords').value=s.seoKeywords||'';$('#seoImage').value=s.seoImage||''} $('#seoForm').onsubmit=e=>{e.preventDefault();store.settings.seoTitle=$('#seoTitle').value.trim();store.settings.seoDescription=$('#seoDescription').value.trim();store.settings.seoKeywords=$('#seoKeywords').value.trim();store.settings.seoImage=$('#seoImage').value.trim();save()};
  function loadSecurity(){const s=store.settings||{};$('#codEnabled').checked=Boolean(s.codEnabled);$('#newAdminPin').value=''} $('#securityForm').onsubmit=e=>{e.preventDefault();const p=$('#newAdminPin').value.trim();if(p&&p.length<4){toast('PIN must be at least 4 characters');return}if(p)store.settings.adminPin=p;store.settings.codEnabled=$('#codEnabled').checked;save();$('#newAdminPin').value='';toast('Security settings saved')};
  $('#resetStore').onclick=()=>{if(confirm('Reset demo catalog, gallery, settings and analytics?')){saveStore(structuredClone(STORE_DEFAULTS));localStorage.removeItem('bookCart');localStorage.removeItem('bookOrders');localStorage.removeItem('bookEnquiries');localStorage.removeItem('lastOrder');localStorage.removeItem('bookAnalytics');sessionStorage.removeItem('adminUnlocked');location.reload()}};
  clearBookForm();loadHome();loadContact();loadDelivery();loadOffers();loadSeo();loadSecurity();dashboard();renderAnalytics();show('dashboard');
})();
