(function(){
  ensureStore(); let store=getStore(); const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
  function toast(m){const t=$('.toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
  function save(){saveStore(store);store=getStore();toast('Saved')}
  function show(id){$$('.admin-section').forEach(x=>x.classList.toggle('hidden',x.id!==id));$$('.admin-side button').forEach(x=>x.classList.toggle('active',x.dataset.target===id)); if(id==='dashboard')dashboard();if(id==='books')books();if(id==='gallery')gallery();if(id==='enquiries')enquiries();}
  $$('.admin-side button').forEach(b=>b.onclick=()=>show(b.dataset.target));
  function dashboard(){const e=JSON.parse(localStorage.getItem('bookEnquiries')||'[]');$('#dashStats').innerHTML=`<div class="stat"><span class="meta">Books</span><b>${store.books.length}</b></div><div class="stat"><span class="meta">Gallery Items</span><b>${store.gallery.length}</b></div><div class="stat"><span class="meta">Enquiries</span><b>${e.length}</b></div>`;}
  function settings(){const s=store.settings;['brandName','tagline','heroTitle','heroText','whatsapp','phone','locationLabel','locationUrl','supportText'].forEach(k=>{const el=$('#s_'+k);if(el)el.value=s[k]||''});}
  $('#settingsForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);for(const [k,v] of fd.entries())store.settings[k]=v;save();}
  function books(){const tb=$('#booksTable');tb.innerHTML=store.books.map(b=>`<tr><td>${b.title}</td><td>${b.author}</td><td>${money(b.price)}</td><td>${b.format}</td><td>${b.category}</td><td><button class="btn btn-light" data-edit="${b.id}">Edit</button> <button class="btn btn-danger" data-del="${b.id}">Delete</button></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editBook(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>{store.books=store.books.filter(x=>x.id!==b.dataset.del);save();books()});}
  function clearForm(){const f=$('#bookForm');f.reset();$('#bookId').value='';$('#bookPreview').innerHTML=''}
  function editBook(id){const b=store.books.find(x=>x.id===id);if(!b)return;$('#bookId').value=b.id;$('#bookTitle').value=b.title;$('#bookAuthor').value=b.author;$('#bookPrice').value=b.price;$('#bookFormat').value=b.format;$('#bookCategory').value=b.category;$('#bookRating').value=b.rating;$('#bookReviews').value=b.reviews;$('#bookDescription').value=b.description||'';$('#bookCoverUrl').value=b.cover||'';$('#bookPreview').innerHTML=b.cover?`<img src="${b.cover}" style="width:100px;height:130px;object-fit:cover;border-radius:10px">`:'';window.scrollTo({top:0,behavior:'smooth'})}
  $('#bookCoverFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{$('#bookCoverData').value=r.result;$('#bookPreview').innerHTML=`<img src="${r.result}" style="width:100px;height:130px;object-fit:cover;border-radius:10px">`};r.readAsDataURL(file)};
  $('#bookForm').onsubmit=e=>{e.preventDefault();const id=$('#bookId').value||('b'+Date.now());const existing=store.books.find(x=>x.id===id);const cover=$('#bookCoverData').value||$('#bookCoverUrl').value||existing?.cover||'';const item={id,title:$('#bookTitle').value.trim()||'Untitled Book',author:$('#bookAuthor').value.trim()||'Author Name',price:Number($('#bookPrice').value||0),format:$('#bookFormat').value,category:$('#bookCategory').value.trim()||'Others',rating:Number($('#bookRating').value||0),reviews:Number($('#bookReviews').value||0),cover,featured:existing?.featured||false,description:$('#bookDescription').value.trim()};if(existing)store.books=store.books.map(x=>x.id===id?item:x);else store.books.push(item);save();clearForm();books();};$('#newBook').onclick=clearForm;
  function gallery(){const el=$('#galleryTable');el.innerHTML=store.gallery.map(g=>`<tr><td>${g.title}</td><td>${g.caption||''}</td><td>${g.image?'Image added':'No image'}</td><td><button class="btn btn-danger" data-gdel="${g.id}">Delete</button></td></tr>`).join('');$$('[data-gdel]').forEach(b=>b.onclick=()=>{store.gallery=store.gallery.filter(x=>x.id!==b.dataset.gdel);save();gallery()});}
  $('#galleryForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const id='g'+Date.now();const img=$('#galleryData').value||$('#galleryUrl').value||'';store.gallery.push({id,title:fd.get('title'),caption:fd.get('caption'),image:img});save();e.target.reset();$('#galleryData').value='';gallery()};$('#galleryFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>$('#galleryData').value=r.result;r.readAsDataURL(file)};
  function enquiries(){const arr=JSON.parse(localStorage.getItem('bookEnquiries')||'[]');$('#enquiriesTable').innerHTML=arr.length?arr.map((x,i)=>`<tr><td>${i+1}</td><td>${x.name||''}</td><td>${x.phone||''}</td><td>${x.email||''}</td><td>${x.message||''}</td><td>${x.date||''}</td></tr>`).join(''):`<tr><td colspan="6">No enquiries yet.</td></tr>`;}
  $('#clearEnquiries').onclick=()=>{localStorage.removeItem('bookEnquiries');enquiries()};
  $('#resetStore').onclick=()=>{if(confirm('Reset demo catalog and settings?')){saveStore(structuredClone(STORE_DEFAULTS));location.reload()}};
  settings();dashboard();show('dashboard');
})();
