(function(){
  ensureStore();
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let store=getStore();
  let books=store.books||[];
  const settings=()=>getStore().settings||{};
  const cart=()=>getCart();
  function toast(msg){const t=$('.toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),1800)}
  function updateCartCount(){const n=cart().reduce((a,x)=>a+Number(x.qty||0),0);$$('.cart-count').forEach(e=>e.textContent=n)}
  function isAvailable(b){return Boolean(b&&b.active!==false&&Number(b.stock||0)>0)}
  function cartQty(id){return Number(cart().find(x=>x.id===id)?.qty||0)}
  function coverHTML(b){return b.cover?`<img src="${esc(b.cover)}" alt="${esc(b.title)}" loading="lazy">`:`<div class="cover-fallback">${esc(b.title)}</div>`}
  function track(name,data){if(typeof trackEvent==='function')trackEvent(name,data)}
  function applySeo(){
    const s=settings();
    const title=s.seoTitle||`${s.brandName||'Your Brand'} | Printed Books`;
    document.title=title;
    const upsert=(name,content)=>{let m=document.head.querySelector(`meta[name="${name}"]`);if(!m){m=document.createElement('meta');m.name=name;document.head.appendChild(m)}m.content=content||''};
    upsert('description',s.seoDescription||'');upsert('keywords',s.seoKeywords||'');
    const og=(p,c)=>{let m=document.head.querySelector(`meta[property="${p}"]`);if(!m){m=document.createElement('meta');m.setAttribute('property',p);document.head.appendChild(m)}m.content=c||''};
    og('og:title',title);og('og:description',s.seoDescription||'');if(s.seoImage)og('og:image',s.seoImage);og('og:type','website');
    let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=location.href.split('#')[0];
  }
  function offerCalculation(items=cart(),bookList=books){
    const s=settings(); if(!s.offerEnabled||s.offerType==='none'||!items.length)return{discount:0,label:'',details:'',type:'none'};
    const units=[];items.forEach(x=>{const b=bookList.find(y=>y.id===x.id);if(!b)return;for(let i=0;i<Number(x.qty||0);i++)units.push({id:b.id,title:b.title,price:Number(b.price||0)})});
    const subtotal=units.reduce((sum,u)=>sum+u.price,0), minPurchase=Number(s.offerMinPurchase||0), cap=Number(s.bogoFreeMaxPrice||500);
    if(s.offerType==='percent10'){if(subtotal<minPurchase)return{discount:0,label:'10% OFF',details:`Buy for ${money(minPurchase)} to unlock 10% off.`,type:'percent10'};const d=Math.round(subtotal*.1*100)/100;return{discount:d,label:'10% OFF',details:`10% discount applied on ${money(subtotal)}.`,type:'percent10'}}
    if(s.offerType==='bogo500'){
      const qualifying=units.filter(u=>u.price>=minPurchase).sort((a,b)=>b.price-a.price);
      if(!qualifying.length||units.length<2)return{discount:0,label:'Buy 1 Get 1',details:`Buy one qualifying book and another book up to ${money(cap)} to activate the offer.`,type:'bogo500'};
      const paid=qualifying[0], candidates=units.filter(u=>u!==paid&&u.price<=cap).sort((a,b)=>b.price-a.price); if(!candidates.length)return{discount:0,label:'Buy 1 Get 1',details:`Add another book up to ${money(cap)} to claim the free book.`,type:'bogo500'};
      return{discount:candidates[0].price,label:'Buy 1 Get 1',details:`Free book up to ${money(cap)} included.`,type:'bogo500'};
    }
    if(s.offerType==='any2get1'){
      if(units.length<3)return{discount:0,label:'Buy Any 2, Get 1 Free',details:'Add 3 book units to activate the free-book offer.',type:'any2get1'};
      const sorted=[...units].sort((a,b)=>b.price-a.price), paidA=sorted[0], paidB=sorted[1], maxFree=Math.max(paidA.price,paidB.price), candidate=sorted.slice(2).filter(u=>u.price<=maxFree).sort((a,b)=>b.price-a.price)[0];
      if(!candidate)return{discount:0,label:'Buy Any 2, Get 1 Free',details:`Add a third book priced up to ${money(maxFree)} to activate the offer.`,type:'any2get1'};
      return{discount:candidate.price,label:'Buy Any 2, Get 1 Free',details:`Free book up to ${money(maxFree)} included.`,type:'any2get1'};
    }
    return{discount:0,label:'',details:'',type:'none'};
  }
  function shippingCalculation(subtotal,distanceKm){
    const s=settings(); if(!s.deliveryEnabled)return{fee:0,label:'Delivery unavailable'};
    if(s.freeShippingEnabled&&subtotal>=Number(s.freeShippingThreshold||0))return{fee:0,label:'FREE'};
    const km=Math.max(.1,Number(distanceKm||1)), raw=km*Number(s.deliveryFeePerKm||0), minimum=Number(s.deliveryMinimumFee||0), fee=Math.max(minimum,Math.round(raw*100)/100);return{fee,label:money(fee)};
  }
  function add(id){
    store=getStore();books=store.books||[];const b=books.find(x=>x.id===id);if(!b)return;if(!isAvailable(b)){toast('This book is out of stock');return}
    const c=cart(),found=c.find(x=>x.id===id),current=Number(found?.qty||0);if(current>=Number(b.stock||0)){toast(`Only ${b.stock} copy/copies available`);return}
    if(found)found.qty++;else c.push({id,qty:1});saveCart(c);updateCartCount();track('add_to_cart',{bookId:id});toast('Added to cart');render();
  }
  function render(){
    const grid=$('#bookGrid');if(!grid)return;store=getStore();books=store.books||[];
    const q=($('#searchInput')?.value||'').toLowerCase().trim(),cat=$('#category')?.value||'',sort=$('#sort')?.value||'featured',max=Number($('#priceRange')?.value||2000);
    let list=books.filter(b=>b.active!==false).filter(b=>(!q||(b.title+' '+b.author+' '+b.category).toLowerCase().includes(q))&&(!cat||b.category===cat)&&Number(b.price||0)<=max);
    if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);else if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);else if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);else list.sort((a,b)=>Number(b.featured)-Number(a.featured));
    $('#bookCount').textContent=`${list.length} Books`;
    grid.innerHTML=list.map(b=>{const qty=cartQty(b.id),available=isAvailable(b);return `<article class="card book-card ${available?'':'is-out-of-stock'}"><div class="book-cover" data-view="${esc(b.id)}">${qty?`<span class="cart-book-badge">${qty}</span>`:''}${coverHTML(b)}</div><div class="book-info"><h3>${esc(b.title)}</h3><div class="meta">${esc(b.author)}</div><div class="rating">★★★★★ <span class="meta">(${Number(b.reviews||0)})</span></div><div class="price">${money(b.price)}</div><div class="format-row"><span class="tag">${esc(b.format)}</span><span class="tag">${esc(b.category)}</span></div><div class="stock-row">${available?`<span class="stock-ok">● In Stock (${Number(b.stock)})</span>`:`<span class="stock-out">● Out of Stock</span>`}</div><div class="btn-row"><button class="btn btn-primary" data-add="${esc(b.id)}" ${available?'':'disabled'}>${available?'Add to Cart':'Out of Stock'}</button><button class="btn btn-gold" data-buy="${esc(b.id)}" ${available?'':'disabled'}>Buy Now</button></div>${b.amazonUrl?`<a class="btn btn-amazon" target="_blank" rel="noopener noreferrer" href="${esc(b.amazonUrl)}">Buy on Amazon ↗</a>`:''}</div></article>`}).join('')||`<div class="panel empty" style="grid-column:1/-1"><div><div class="emoji">📚</div><h3>No books found</h3><p class="muted">Try another search or filter.</p></div></div>`;
    $$('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));
    $$('[data-buy]').forEach(b=>b.onclick=()=>{const target=books.find(x=>x.id===b.dataset.buy);if(!isAvailable(target))return;track('buy_now',{bookId:b.dataset.buy});add(b.dataset.buy);location.href='cart.html'});
    $$('[data-view]').forEach(e=>e.onclick=()=>openBook(e.dataset.view));
    const s=settings();if($('#offerBanner'))$('#offerBanner').innerHTML=s.offerEnabled&&s.offerType!=='none'?`<strong>${esc(s.offerTitle||offerCalculation([{id:'dummy',qty:0}],books).label||'Special Offer')}</strong><span>${esc(s.offerText||'Automatic offer available at checkout.')}</span>`:'';
  }
  function openBook(id){const b=books.find(x=>x.id===id);if(!b)return;track('book_view',{bookId:id});const old=$('#bookModal');if(old)old.remove();const wa=`https://wa.me/${String(settings().whatsapp||'').replace(/\D/g,'')}?text=${encodeURIComponent('Hello, I am enquiring about '+b.title)}`;const m=document.createElement('div');m.id='bookModal';m.className='modal-backdrop';m.innerHTML=`<div class="modal-card"><button class="modal-close" aria-label="Close">×</button><div class="modal-grid"><div class="modal-cover">${coverHTML(b)}</div><div><div class="admin-eyebrow">BOOK DETAILS</div><h2>${esc(b.title)}</h2><p class="meta">${esc(b.author)} · ${esc(b.format)} · ${esc(b.category)}</p><div class="rating">★★★★★ <span class="meta">(${Number(b.reviews||0)} reviews)</span></div><div class="price" style="margin-top:8px">${money(b.price)}</div><p style="line-height:1.7">${esc(b.description||'')}</p><div class="stock-row">${isAvailable(b)?`<span class="stock-ok">● In Stock (${b.stock})</span>`:`<span class="stock-out">● Out of Stock</span>`}</div><div class="btn-row" style="margin-top:16px"><button class="btn btn-primary" ${isAvailable(b)?'':'disabled'} id="modalAdd">Add to Cart</button>${b.amazonUrl?`<a class="btn btn-amazon" target="_blank" rel="noopener noreferrer" href="${esc(b.amazonUrl)}">Buy on Amazon ↗</a>`:''}</div></div></div></div>`;document.body.appendChild(m);$('.modal-close').onclick=()=>m.remove();m.addEventListener('click',e=>{if(e.target===m)m.remove()});$('#modalAdd')?.addEventListener('click',()=>{add(id);m.remove()})}
  function initBooks(){if(!$('#bookGrid'))return;track('page_view',{page:location.pathname});store=getStore();books=store.books||[];const cats=[...new Set(books.map(b=>b.category).filter(Boolean))];$('#category').innerHTML='<option value="">All Categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#searchInput')?.addEventListener('input',render);$('#sort')?.addEventListener('change',render);$('#category')?.addEventListener('change',render);$('#priceRange')?.addEventListener('input',e=>{$('#priceMax').textContent=money(e.target.value)+'+';render()});render()}
  function cartRender(){if(!$('#cartList'))return;track('page_view',{page:location.pathname});store=getStore();books=store.books||[];const c=cart(),byId=id=>books.find(b=>b.id===id),list=$('#cartList');if(!c.length){list.innerHTML=`<div class="empty"><div><div class="emoji">🛒</div><h2>Your cart is empty</h2><p class="muted">Choose a book and come back here.</p><a class="btn btn-gold" href="index.html">Continue Shopping</a></div></div>`;$('#summary').innerHTML=`<h3>Order Summary</h3><p class="muted">Your cart is empty.</p><a class="btn btn-gold" href="index.html">Browse Books</a>`;return}list.innerHTML=c.map(x=>{const b=byId(x.id);if(!b)return '';return `<div class="cart-item"><div class="cart-thumb">${coverHTML(b)}</div><div><h3 style="margin:0 0 4px">${esc(b.title)}</h3><div class="meta">${esc(b.author)} · ${esc(b.format)}</div><div class="meta">${money(b.price)} each</div><div class="stock-row">${isAvailable(b)?`<span class="stock-ok">${b.stock} available</span>`:`<span class="stock-out">Out of stock</span>`}</div></div><div class="qty"><button data-minus="${esc(b.id)}">−</button><b>${x.qty}</b><button data-plus="${esc(b.id)}">+</button></div><div class="price">${money(b.price*x.qty)} <button class="btn btn-danger" style="margin-left:8px;padding:7px 9px" data-remove="${esc(b.id)}">×</button></div></div>`}).join('');$$('#cartList [data-minus]').forEach(e=>e.onclick=()=>changeQty(e.dataset.minus,-1));$$('#cartList [data-plus]').forEach(e=>e.onclick=()=>changeQty(e.dataset.plus,1));$$('#cartList [data-remove]').forEach(e=>e.onclick=()=>removeItem(e.dataset.remove));const subtotal=c.reduce((s,x)=>{const b=byId(x.id);return s+(b?b.price*x.qty:0)},0),offer=offerCalculation(c,books),shipping=shippingCalculation(subtotal,1),total=Math.max(0,subtotal-offer.discount+shipping.fee);$('#summary').innerHTML=`<h3>Order Summary</h3><div class="summary-line"><span>Items</span><b>${money(subtotal)}</b></div><div class="summary-line"><span>Offer</span><b>${offer.discount?'-'+money(offer.discount):'—'}</b></div><div class="summary-line"><span>Shipping</span><b>${shipping.label}</b></div>${offer.details?`<div class="notice">${esc(offer.details)}</div>`:''}<div class="summary-line summary-total"><span>Total</span><b>${money(total)}</b></div><button class="btn btn-gold" style="width:100%;margin-top:12px" id="toCheckout">Proceed to Checkout →</button>`;$('#toCheckout').onclick=()=>{track('checkout_start');location.href='checkout.html'};}
  function changeQty(id,d){const c=cart(),x=c.find(i=>i.id===id),b=books.find(y=>y.id===id);if(!x||!b)return;x.qty+=d;if(x.qty<=0)return removeItem(id);if(x.qty>Number(b.stock||0)){x.qty=Number(b.stock||0);toast(`Only ${b.stock} available`)}saveCart(c);updateCartCount();cartRender()}
  function removeItem(id){saveCart(cart().filter(x=>x.id!==id));updateCartCount();cartRender()}
  function initCart(){if(!$('#cartList'))return;$('#clearCart')?.addEventListener('click',()=>{saveCart([]);updateCartCount();cartRender()});cartRender()}
  function checkout(){
    if(!$('#checkoutForm'))return;track('page_view',{page:location.pathname});store=getStore();books=store.books||[];const c=cart();if(!c.length){location.href='index.html';return}
    const paymentWrap=document.querySelector('[data-payment-options]');
    if(paymentWrap){paymentWrap.innerHTML=`<label class="filter-option"><input type="radio" name="payment" value="UPI" checked> UPI (Google Pay, PhonePe, Paytm)</label><label class="filter-option"><input type="radio" name="payment" value="Card"> Credit / Debit Card</label><label class="filter-option"><input type="radio" name="payment" value="Net Banking"> Net Banking</label><label class="filter-option"><input type="radio" name="payment" value="Wallet"> Wallets</label>${settings().codEnabled?'<label class="filter-option"><input type="radio" name="payment" value="COD"> Cash on Delivery</label>':''}`}
    function renderCheckoutSummary(){const currentCart=cart(),subtotal=currentCart.reduce((sum,x)=>{const b=books.find(y=>y.id===x.id);return sum+(b?b.price*x.qty:0)},0),distance=Math.max(.1,Number($('#distanceKm')?.value||1)),offer=offerCalculation(currentCart,books),shipping=shippingCalculation(subtotal,distance),total=Math.max(0,subtotal-offer.discount+shipping.fee);$('#checkoutSummary').innerHTML=`<h3>Order Summary</h3>${currentCart.map(x=>{const b=books.find(b=>b.id===x.id);return b?`<div class="summary-line"><span>${esc(b.title)} × ${x.qty}</span><b>${money(b.price*x.qty)}</b></div>`:''}).join('')}<div class="summary-line"><span>Subtotal</span><b>${money(subtotal)}</b></div><div class="summary-line"><span>Offer</span><b>${offer.discount?'-'+money(offer.discount):'—'}</b></div><div class="summary-line"><span>Delivery</span><b>${shipping.label}</b></div>${offer.details?`<div class="notice">${esc(offer.details)}</div>`:''}<div class="summary-line summary-total"><span>Total</span><b>${money(total)}</b></div>`;$('#payBtn').textContent=`Pay ${money(total)} Securely`;if($('#distanceKm'))$('#distanceKm').disabled=!settings().deliveryEnabled;if($('#distanceField'))$('#distanceField').classList.toggle('hidden',!settings().deliveryEnabled);if($('#deliveryHelp'))$('#deliveryHelp').textContent=settings().deliveryEnabled?`Delivery fee: ${money(settings().deliveryFeePerKm||0)} per km. Minimum ${money(settings().deliveryMinimumFee||0)}.`:'Delivery is currently disabled.';const p=[...document.querySelectorAll('input[name="payment"]')];p.forEach(r=>{if(r.value==='COD'&&!settings().codEnabled)r.closest('label')?.remove()});$('#payBtn').disabled=!settings().deliveryEnabled;}
    renderCheckoutSummary();$('#distanceKm')?.addEventListener('input',renderCheckoutSummary);
    $('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();if(!settings().deliveryEnabled){toast('Delivery is currently unavailable');return}store=getStore();books=store.books||[];const currentCart=cart();for(const item of currentCart){const b=books.find(x=>x.id===item.id);if(!b||!isAvailable(b)||item.qty>Number(b.stock||0)){toast('Please check book availability');return}}const fd=new FormData(e.target);for(const k of ['name','phone','address','city','state','pincode'])if(!String(fd.get(k)||'').trim()){toast('Please fill required fields');return}const distanceKm=Math.max(.1,Number(fd.get('distanceKm')||1)),subtotal=currentCart.reduce((sum,x)=>{const b=books.find(y=>y.id===x.id);return sum+(b?b.price*x.qty:0)},0),off=offerCalculation(currentCart,books),ship=shippingCalculation(subtotal,distanceKm),finalTotal=Math.max(0,subtotal-off.discount+ship.fee),payment=fd.get('payment')||'UPI';if(payment==='COD'&&!settings().codEnabled){toast('COD is not available');return}const order={id:'ORD-'+Date.now().toString().slice(-8),date:new Date().toLocaleString('en-IN'),customer:Object.fromEntries(fd.entries()),items:currentCart,total:finalTotal,subtotal,discount:off.discount,discountLabel:off.label,shipping:ship.fee,paymentStatus:'Demo',status:'Placed'};localStorage.setItem('lastOrder',JSON.stringify(order));const existingOrders=JSON.parse(localStorage.getItem('bookOrders')||'[]');existingOrders.unshift(order);localStorage.setItem('bookOrders',JSON.stringify(existingOrders.slice(0,200)));books=books.map(b=>{const item=currentCart.find(x=>x.id===b.id);return item?{...b,stock:Math.max(0,Number(b.stock||0)-Number(item.qty||0))}:b});store.books=books;saveStore(store);saveCart([]);track('order_placed',{orderId:order.id});location.href='success.html'});
  }
  function success(){if(!$('#successBox'))return;track('page_view',{page:location.pathname});const o=JSON.parse(localStorage.getItem('lastOrder')||'null');if(!o){location.href='index.html';return}store=getStore();books=store.books||[];$('#successBox').innerHTML=`<div class="success-icon">✓</div><h1>Order Placed Successfully!</h1><p>Thank you for your order. Your books will be shipped soon.</p><div class="timeline"><div class="step"><b>Order Placed</b><br><span class="meta">${esc(o.date)}</span></div><div class="step"><b>Packed</b><br><span class="meta">Processing</span></div><div class="step"><b>Shipped</b><br><span class="meta">Tracking soon</span></div><div class="step"><b>Delivered</b><br><span class="meta">Est. 3–7 days</span></div></div>`;$('#orderDetails').innerHTML=`<h2>Order Details</h2><div class="summary-line"><span>Order ID</span><b>${esc(o.id)}</b></div>${(o.items||[]).map(x=>{const b=books.find(b=>b.id===x.id);return `<div class="summary-line"><span>${esc(b?.title||x.id)} × ${x.qty}</span><b>${money((b?.price||0)*x.qty)}</b></div>`}).join('')}<div class="summary-line"><span>Offer</span><b>${o.discount?'-'+money(o.discount):'—'}</b></div><div class="summary-line"><span>Delivery</span><b>${o.shipping?money(o.shipping):'FREE'}</b></div><div class="summary-line summary-total"><span>Total Paid</span><b>${money(o.total)}</b></div>`;$('#addressBox').innerHTML=`<h3>Shipping Address</h3><p style="line-height:1.6;margin-bottom:0">${esc(o.customer.name)}<br>${esc(o.customer.address)}<br>${esc(o.customer.city)}, ${esc(o.customer.state)} - ${esc(o.customer.pincode)}<br>Mobile: ${esc(o.customer.phone)}</p>`}
  function common(){updateCartCount();applySeo();const s=getStore().settings||{};$$('.brand-name').forEach(e=>e.textContent=s.brandName||'Your Brand');$$('.tagline').forEach(e=>e.textContent=s.tagline||'');$$('.whatsapp').forEach(e=>e.href=`https://wa.me/${String(s.whatsapp||'').replace(/\D/g,'')}`);$$('.phone').forEach(e=>e.href=`tel:${s.phone||''}`);$$('.location').forEach(e=>e.href=s.locationUrl||'#');$$('.location-text').forEach(e=>e.textContent=s.address||'');$$('.location-label').forEach(e=>e.textContent=s.locationLabel||'Location');$('#heroTitle')&&($('#heroTitle').textContent=s.heroTitle||'Discover Books That Inspire Change');$('#heroText')&&($('#heroText').textContent=s.heroText||'');$('#supportText')&&($('#supportText').textContent=s.supportText||'');$$('.delivery-status').forEach(e=>e.textContent=s.deliveryEnabled?'Delivery Available':'Delivery Currently Disabled')}
  initBooks();initCart();checkout();success();common();
})();
