(function(){
  const store=ensureStore();
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
  let books=store.books||[];
  function cart(){return getCart();}
  function updateCartCount(){const n=cart().reduce((a,x)=>a+x.qty,0); $$('.cart-count').forEach(e=>e.textContent=n);}
  function toast(msg){const t=$('.toast'); if(!t)return; t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),1800)}
  function coverHTML(b){return b.cover?`<img src="${b.cover}" alt="${b.title}">`:`<div class="cover-fallback">${b.title}</div>`}
  function add(id){const b=books.find(x=>x.id===id);if(!b)return;const c=cart();const found=c.find(x=>x.id===id);if(found)found.qty++;else c.push({id,qty:1});saveCart(c);updateCartCount();toast('Added to cart');}
  function render(){
    const grid=$('#bookGrid');if(!grid)return;
    const q=($('#searchInput')?.value||'').toLowerCase(); const cat=$('#category')?.value||''; const sort=$('#sort')?.value||'featured'; const max=Number($('#priceRange')?.value||2000);
    let list=books.filter(b=>(!q||(b.title+' '+b.author+' '+b.category).toLowerCase().includes(q))&&(!cat||b.category===cat)&&b.price<=max);
    if(sort==='price-asc')list.sort((a,b)=>a.price-b.price); else if(sort==='price-desc')list.sort((a,b)=>b.price-a.price); else if(sort==='rating')list.sort((a,b)=>b.rating-a.rating); else list.sort((a,b)=>Number(b.featured)-Number(a.featured));
    $('#bookCount').textContent=`${list.length} Books`;
    grid.innerHTML=list.map(b=>`<article class="card book-card"><div class="book-cover">${coverHTML(b)}</div><div class="book-info"><h3>${b.title}</h3><div class="meta">${b.author}</div><div class="rating">★★★★★ <span class="meta">(${b.reviews})</span></div><div class="price">${money(b.price)}</div><div class="format-row"><span class="tag">${b.format}</span><span class="tag">${b.category}</span></div><div class="btn-row"><button class="btn btn-primary" data-add="${b.id}">Add to Cart</button><button class="btn btn-gold" data-buy="${b.id}">Buy Now</button></div></div></article>`).join('') || `<div class="panel empty" style="grid-column:1/-1"><div><div class="emoji">📚</div><h3>No books found</h3><p class="muted">Try another search or filter.</p></div></div>`;
    $$('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add)); $$('[data-buy]').forEach(b=>b.onclick=()=>{add(b.dataset.buy);location.href='cart.html'});
  }
  function initBooks(){
    if(!$('#bookGrid'))return;
    const cats=[...new Set(books.map(b=>b.category))]; if($('#category')) $('#category').innerHTML='<option value="">All Categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');
    $('#searchInput')?.addEventListener('input',render); $('#sort')?.addEventListener('change',render); $('#category')?.addEventListener('change',render); $('#priceRange')?.addEventListener('input',e=>{$('#priceMax').textContent=money(e.target.value)+'+';render()}); render();
  }
  function cartRender(){
    if(!$('#cartList'))return; const c=cart(); const byId=id=>books.find(b=>b.id===id); const list=$('#cartList');
    if(!c.length){list.innerHTML=`<div class="empty"><div><div class="emoji">🛒</div><h2>Your cart is empty</h2><p class="muted">Choose a book and come back here.</p><a class="btn btn-gold" href="index.html">Continue Shopping</a></div></div>`; $('#summary').innerHTML=`<h3>Order Summary</h3><p class="muted">Your cart is empty.</p><a class="btn btn-gold" href="index.html">Browse Books</a>`; return;}
    list.innerHTML=c.map(x=>{const b=byId(x.id);return `<div class="cart-item"><div class="cart-thumb">${b.title}</div><div><h3 style="margin:0 0 4px">${b.title}</h3><div class="meta">${b.author} · ${b.format}</div><div class="meta">${money(b.price)} each</div></div><div class="qty"><button data-minus="${b.id}">−</button><b>${x.qty}</b><button data-plus="${b.id}">+</button></div><div class="price">${money(b.price*x.qty)} <button class="btn btn-danger" style="margin-left:8px;padding:7px 9px" data-remove="${b.id}">×</button></div></div>`}).join('');
    $$('#cartList [data-minus]').forEach(e=>e.onclick=()=>changeQty(e.dataset.minus,-1)); $$('#cartList [data-plus]').forEach(e=>e.onclick=()=>changeQty(e.dataset.plus,1)); $$('#cartList [data-remove]').forEach(e=>e.onclick=()=>removeItem(e.dataset.remove));
    const subtotal=c.reduce((s,x)=>{const b=byId(x.id);return s+b.price*x.qty},0); const shipping=subtotal>=999?0:40; const total=subtotal+shipping;
    $('#summary').innerHTML=`<h3>Order Summary</h3><div class="summary-line"><span>Items</span><b>${money(subtotal)}</b></div><div class="summary-line"><span>Shipping</span><b>${shipping?money(shipping):'FREE'}</b></div><div class="summary-line summary-total"><span>Total</span><b>${money(total)}</b></div><button class="btn btn-gold" style="width:100%;margin-top:12px" id="toCheckout">Proceed to Checkout →</button>`;
    $('#toCheckout').onclick=()=>location.href='checkout.html';
  }
  function changeQty(id,d){const c=cart();const x=c.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)return removeItem(id);saveCart(c);updateCartCount();cartRender()}
  function removeItem(id){saveCart(cart().filter(x=>x.id!==id));updateCartCount();cartRender()}
  function initCart(){ if(!$('#cartList'))return; $('#clearCart')?.addEventListener('click',()=>{saveCart([]);updateCartCount();cartRender()});cartRender(); }
  function checkout(){ if(!$('#checkoutForm'))return; const c=cart(); if(!c.length){location.href='index.html';return;} const subtotal=c.reduce((s,x)=>{const b=books.find(b=>b.id===x.id);return s+b.price*x.qty},0);const shipping=subtotal>=999?0:40;const total=subtotal+shipping; $('#checkoutSummary').innerHTML=`<h3>Order Summary</h3>${c.map(x=>{const b=books.find(b=>b.id===x.id);return `<div class="summary-line"><span>${b.title} × ${x.qty}</span><b>${money(b.price*x.qty)}</b></div>`}).join('')}<div class="summary-line"><span>Shipping</span><b>${shipping?money(shipping):'FREE'}</b></div><div class="summary-line summary-total"><span>Total</span><b>${money(total)}</b></div>`; $('#payBtn').textContent=`Pay ${money(total)} Securely`;
    $('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);if(!fd.get('name')||!fd.get('phone')||!fd.get('address')||!fd.get('city')||!fd.get('state')||!fd.get('pincode'))return toast('Please fill required fields');const order={id:'ORD-'+Date.now().toString().slice(-8),date:new Date().toLocaleString('en-IN'),customer:Object.fromEntries(fd.entries()),items:c,total};localStorage.setItem('lastOrder',JSON.stringify(order));const existingOrders=JSON.parse(localStorage.getItem('bookOrders')||'[]');existingOrders.unshift(order);localStorage.setItem('bookOrders',JSON.stringify(existingOrders.slice(0,200)));saveCart([]);location.href='success.html'});
  }
  function success(){if(!$('#successBox'))return;const o=JSON.parse(localStorage.getItem('lastOrder')||'null');if(!o){location.href='index.html';return;}$('#successBox').innerHTML=`<div class="success-icon">✓</div><h1>Order Placed Successfully!</h1><p>Thank you for your order. Your books will be shipped soon.</p><div class="timeline"><div class="step"><b>Order Placed</b><br><span class="meta">${o.date}</span></div><div class="step"><b>Packed</b><br><span class="meta">Processing</span></div><div class="step"><b>Shipped</b><br><span class="meta">Tracking soon</span></div><div class="step"><b>Delivered</b><br><span class="meta">Est. 3–7 days</span></div></div>`;$('#orderDetails').innerHTML=`<h2>Order Details</h2><div class="summary-line"><span>Order ID</span><b>${o.id}</b></div>${o.items.map(x=>{const b=books.find(b=>b.id===x.id);return `<div class="summary-line"><span>${b?.title||x.id} × ${x.qty}</span><b>${money((b?.price||0)*x.qty)}</b></div>`}).join('')}<div class="summary-line summary-total"><span>Total Paid</span><b>${money(o.total)}</b></div>`;$('#addressBox').innerHTML=`<h3>Shipping Address</h3><p style="line-height:1.6;margin-bottom:0">${o.customer.name}<br>${o.customer.address}<br>${o.customer.city}, ${o.customer.state} - ${o.customer.pincode}<br>Mobile: ${o.customer.phone}</p>`}
  function common(){updateCartCount();const s=getStore().settings; $$('.brand-name').forEach(e=>e.textContent=s.brandName);$$('.tagline').forEach(e=>e.textContent=s.tagline);$$('.whatsapp').forEach(e=>e.href=`https://wa.me/${String(s.whatsapp||'').replace(/\D/g,'')}`);$$('.phone').forEach(e=>e.href=`tel:${s.phone||''}`);$$('.location').forEach(e=>e.href=s.locationUrl||'#');$('#heroTitle')&&(($('#heroTitle').textContent=s.heroTitle),($('#heroText').textContent=s.heroText));$('#supportText')&&($('#supportText').textContent=s.supportText)}
  initBooks();initCart();checkout();success();common();
})();
