(function(){
  const cartKey='bookstore_cart_v1';
  const state={ books:window.BOOKS||[], cart:JSON.parse(localStorage.getItem(cartKey)||'[]'), category:'All Books', query:'', sort:'featured', maxPrice:2000 };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const money=n=>`₹${Number(n).toLocaleString('en-IN')}`;
  const save=()=>{localStorage.setItem(cartKey,JSON.stringify(state.cart)); updateCartBadge();};
  const findBook=id=>state.books.find(b=>b.id===id);
  const cartQty=id=>(state.cart.find(i=>i.id===id)||{}).qty||0;
  function cartCount(){return state.cart.reduce((a,i)=>a+i.qty,0)}
  function updateCartBadge(){$$('.cart-count').forEach(el=>el.textContent=cartCount())}
  function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
  function addToCart(id,qty=1){const item=state.cart.find(i=>i.id===id);if(item)item.qty+=qty;else state.cart.push({id,qty});save();toast('Added to cart');}
  function setQty(id,qty){const item=state.cart.find(i=>i.id===id);if(!item)return;if(qty<=0)state.cart=state.cart.filter(i=>i.id!==id);else item.qty=qty;save();}
  function subtotal(){return state.cart.reduce((sum,i)=>{const b=findBook(i.id);return sum+(b?b.price*i.qty:0)},0)}
  function shipping(){return subtotal()===0?0:(subtotal()>=999?0:40)}
  function total(){return subtotal()+shipping()}
  function coverStyle(b){return `background:linear-gradient(145deg,${b.cover[0]} 0%,${b.cover[1]} 72%,${b.cover[2]} 100%)`}
  function stars(r){const rounded=Math.round(r);return '★'.repeat(rounded)+'☆'.repeat(5-rounded)}
  function bookCard(b){return `<article class="book-card"><div class="cover-wrap"><div class="book-cover" style="${coverStyle(b)}"><span>${b.title}</span></div>${b.badge?`<span class="badge">${b.badge}</span>`:''}<button class="wish" aria-label="Wishlist">♡</button></div><div class="book-title">${b.title}</div><div class="author">${b.author}</div><div class="rating">${stars(b.rating)} <span>${b.rating} (${b.reviews})</span></div><div class="price">${money(b.price)} ${b.oldPrice?`<del>${money(b.oldPrice)}</del>`:''}</div><div class="formats"><span class="format active">${b.format}</span><span class="format">${b.format==='Paperback'?'Hardcover':'Paperback'}</span></div><div class="actions"><button class="btn btn-dark add-btn" data-id="${b.id}">🛒 Add to Cart</button><button class="btn btn-gold buy-btn" data-id="${b.id}">Buy Now</button></div></article>`}
  function renderBooks(){const grid=$('#bookGrid');if(!grid)return;let list=state.books.filter(b=>(state.category==='All Books'||b.category===state.category)&&b.price<=state.maxPrice&&(b.title+' '+b.author+' '+b.category).toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(state.sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(state.sort==='rating')list.sort((a,b)=>b.rating-a.rating);$('#bookCount').textContent=`${list.length} Books`;grid.innerHTML=list.map(bookCard).join('')||`<div class="panel pad" style="grid-column:1/-1;text-align:center">No books match your filters.</div>`; $$('.add-btn').forEach(btn=>btn.onclick=()=>addToCart(btn.dataset.id));$$('.buy-btn').forEach(btn=>btn.onclick=()=>{addToCart(btn.dataset.id);location.href='cart.html'});$$('.wish').forEach(btn=>btn.onclick=()=>toast('Wishlist will be available later'));$$('.book-cover').forEach(el=>el.onclick=()=>toast('Book details preview'));}
  function renderCart(){const wrap=$('#cartItems'), summary=$('#summary');if(!wrap||!summary)return;if(!state.cart.length){wrap.innerHTML=`<div class="empty"><div class="big">🛒</div><h2>Your cart is empty</h2><p class="muted">Choose a book and come back here.</p><a class="btn btn-gold" href="books.html" style="display:inline-grid;place-items:center;min-width:190px">Continue Shopping</a></div>`;summary.innerHTML='';return;}wrap.innerHTML=state.cart.map(i=>{const b=findBook(i.id);return `<div class="cart-item"><div class="thumb" style="background:linear-gradient(145deg,${b.cover[0]},${b.cover[1]})">${b.title}</div><div><h4>${b.title}</h4><div class="author">${b.author}</div><div class="formats"><span class="format active">${b.format}</span></div><div class="price">${money(b.price)}</div></div><div class="qty"><button data-act="minus" data-id="${b.id}">−</button><span>${i.qty}</span><button data-act="plus" data-id="${b.id}">+</button></div><div class="item-price price">${money(b.price*i.qty)}</div><button class="remove" data-act="remove" data-id="${b.id}" aria-label="Remove">🗑</button></div>`}).join('');summary.innerHTML=`<div class="summary-box"><h2>Order Summary</h2><div class="summary-row"><span>Items (${cartCount()} books)</span><strong>${money(subtotal())}</strong></div><div class="summary-row"><span>Shipping Charges</span><strong>${shipping()===0?'Free':money(shipping())}</strong></div><div class="coupon-row"><input id="coupon" placeholder="Coupon code"><button class="btn btn-outline" id="applyCoupon">Apply</button></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="summary-row"><span style="font-weight:800">Total Amount</span><span class="summary-total">${money(total())}</span></div><button class="btn btn-gold btn-block" id="checkoutBtn" style="margin-top:15px">🔒 Proceed to Checkout →</button><div class="muted" style="font-size:12px;text-align:center;margin-top:12px">Secure checkout • Guest purchase</div></div>`;$$('[data-act]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.id,act=btn.dataset.act;const q=cartQty(id);if(act==='plus')setQty(id,q+1);if(act==='minus')setQty(id,q-1);if(act==='remove')setQty(id,0);renderCart();});$('#checkoutBtn').onclick=()=>location.href='checkout.html';$('#applyCoupon').onclick=()=>toast('Coupons will be connected later');}
  function setupCheckout(){const wrap=$('#checkoutForm'), order=$('#checkoutSummary');if(!wrap||!order)return;if(!state.cart.length){location.href='books.html';return}order.innerHTML=state.cart.map(i=>{const b=findBook(i.id);return `<div class="summary-row"><span>${b.title} × ${i.qty}</span><strong>${money(b.price*i.qty)}</strong></div>`}).join('')+`<hr style="border:0;border-top:1px solid var(--line)"><div class="summary-row"><span>Subtotal</span><strong>${money(subtotal())}</strong></div><div class="summary-row"><span>Shipping</span><strong>${shipping()===0?'Free':money(shipping())}</strong></div><div class="summary-row"><span>Total</span><span class="summary-total">${money(total())}</span></div>`;wrap.onsubmit=e=>{e.preventDefault();if(!wrap.checkValidity()){wrap.reportValidity();return}const fd=new FormData(wrap);const orderData={id:'ORD-'+Date.now().toString().slice(-8),name:fd.get('name'),mobile:fd.get('mobile'),email:fd.get('email'),address:fd.get('address'),city:fd.get('city'),state:fd.get('state'),pincode:fd.get('pincode'),payment:fd.get('payment'),items:state.cart.map(i=>({...i})),total:total(),createdAt:new Date().toISOString()};localStorage.setItem('last_order',JSON.stringify(orderData));state.cart=[];save();location.href='success.html'};$$('input[name="payment"]').forEach(r => r.addEventListener('change', () => { $$('.payment-option').forEach(o => o.classList.toggle('selected', o.querySelector('input').checked)); }));}
  function setupSuccess(){const data=JSON.parse(localStorage.getItem('last_order')||'null');const main=$('#successMain');if(!main)return;if(!data){main.innerHTML=`<div class="panel pad empty"><div class="big">📚</div><h2>No recent order</h2><a href="books.html" class="btn btn-gold" style="display:inline-grid;place-items:center">Go to Books</a></div>`;return}const books=(data.items||[]).map(i=>{const b=findBook(i.id);return `<div class="cart-item"><div class="thumb" style="background:linear-gradient(145deg,${b.cover[0]},${b.cover[1]})">${b.title}</div><div><h4>${b.title}</h4><div class="author">${b.author}</div><div class="author">${b.format} • Qty ${i.qty}</div></div><div></div><div class="item-price price">${money(b.price*i.qty)}</div><div></div></div>`}).join('');main.innerHTML=`<div class="success-hero"><div class="success-icon">✓</div><div><h1>Order Placed Successfully!</h1><p>Thank you for your order. Your books will be shipped soon.</p></div></div><div class="success-layout"><section class="panel pad"><h2>Order Details</h2><div class="summary-row"><span>Order ID</span><strong>#${data.id}</strong></div>${books}<hr style="border:0;border-top:1px solid var(--line);margin:15px 0"><div class="summary-row"><span>Total Paid</span><span class="summary-total">${money(data.total)}</span></div></section><aside class="panel pad"><div class="status-box"><h3 style="color:#177846">Your Order is Confirmed</h3><p class="muted">We will pack and ship your books shortly.</p><div class="timeline"><div class="step done"><div class="dot">✓</div><small>Order Placed</small></div><div class="step active"><div class="dot">2</div><small>Packed</small></div><div class="step"><div class="dot">3</div><small>Shipped</small></div><div class="step"><div class="dot">4</div><small>Delivered</small></div></div></div><div class="address-box"><h3>Shipping Address</h3><div>${data.name}<br>${data.address}<br>${data.city}, ${data.state} - ${data.pincode}<br>Mobile: ${data.mobile}</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px"><div class="panel pad" style="box-shadow:none;background:#f8fbff"><strong>Estimated Delivery</strong><div class="muted">3–7 business days</div></div><div class="panel pad" style="box-shadow:none;background:#f8fbff"><strong>Payment</strong><div class="muted">${data.payment||'Selected method'}</div></div></div><a href="books.html" class="btn btn-gold btn-block" style="display:grid;place-items:center;margin-top:16px">📖 Continue Shopping →</a></aside></div>`}
  function setupBooks(){if(!$('#bookGrid'))return;const catBox=$('#categoryFilters');catBox.innerHTML=window.CATEGORIES.map((c,i)=>`<label class="filter-option"><input type="radio" name="cat" value="${c}" ${i===0?'checked':''}>${c}</label>`).join('');$$('input[name="cat"]').forEach(x=>x.onchange=()=>{state.category=x.value;renderBooks()});$('#searchInput').oninput=e=>{state.query=e.target.value;renderBooks()};$('#sort').onchange=e=>{state.sort=e.target.value;renderBooks()};$('#priceRange').oninput=e=>{state.maxPrice=Number(e.target.value);$('#priceMax').textContent=money(state.maxPrice)+'+';renderBooks()};renderBooks();}
  document.addEventListener('DOMContentLoaded',()=>{updateCartBadge();setupBooks();renderCart();setupCheckout();setupSuccess();$('#clearCart')?.addEventListener('click',()=>{state.cart=[];save();renderCart()});$('#mobileMenu')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));});
})();
